### ISSUE TITLE
Organization and Goals

### ISSUE THREAD

**Issue by corgimaman** [corgimaman/groupProject#2]
1. Who is doing what
2. Wireframe
3. What we are going to accomplish

**Comment by ferick8246** [comment]
Let US welcome team-mongoose 
Jesse Ceniceros User Interface 
Ida Shalilian JR. Developer/Business Analyst
Kevin Henley JR. Developer
Erick Flores Project Manager/Business Analysts 

Jesse will build a the wireframe using CSS and HTML 

Ida and Kevin will be working on JavaScript code and working on the API as well
